### ISSUE TITLE
server出错时的细节处理

### ISSUE THREAD

**Issue by SMbey0nd** [spmjs/spm-server#15]
目前遇到很多跟细节相关的问题：

比如server启动后，调试过程中突然发现某些js突然出现类似报错"require not defined"，查看下发现是该文件没有按预期加载头部define部分，再向后排查，最终发现是server过程中的某一个output文件内容解析出错导致server出现error，从而后续的js都会受影响无法正常解析。而这个出错提示又非常不清晰。

建议如下：

1. server过程中如果出现问题，同时可以考虑终止掉server服务（目前是还可以正常浏览但没有加载define头部，就会出现报错，经验少的同学还是挺难以排查问题的），这样给用户的提示比较明确。
1. 出问题后，需要有明显的友好提示。例如页面上也可以考虑输出一些提示内容。控制台内的提示需要明显一些（标红或者黄色处理）。目前是白色，很不明显。

**Comment by sorrycc** [comment]
增加标红处理：
![](https://t.alipayobjects.com/images/T186XeXaxcXXXXXXXX.png)
