### ISSUE TITLE
koa导致安装起来运行不了

### ISSUE THREAD

**Issue by xuhuan** [spmjs/spm-server#21]
![image](https://cloud.githubusercontent.com/assets/1960194/5894917/004a3540-a54b-11e4-8703-96b137e93322.png)

如图，koa和koa-server-index要求的node版本竟然是0.11.x，nodejs官方最新的也就0.10.35，怎么破？

![image](https://cloud.githubusercontent.com/assets/1960194/5894948/87ea60ec-a54b-11e4-903b-c47dc364c537.png)
执行后错误如图。

**Comment by sorrycc** [comment]
WARN 应该不影响使用吧，推荐升级到 0.11.x 。

**Comment by xuhuan** [comment]
怎么升级？系统是win2003的，http://nodejs.org 只提供0.10.35下载。。。。

**Comment by afc163** [comment]
https://github.com/normalize/native-or-bluebird#native-or-bluebird

> The goal of this library is to be able to eventually remove this line from your code and use native Promises, allowing you to to write future-compatible code with ease. You should install bluebird in your libraries for maximum compatibility.

@sorrycc

**Comment by sorrycc** [comment]
提示安装 bluebird 的话，执行下 `npm i bluebird -g` 应该就可以了。

升级到 node 0.11，可以参考下这些地址：

- http://blog.nodejs.org/release/
- https://github.com/hakobera/nvmw

**Comment by afc163** [comment]
建议 spm-server 加入这个依赖，现在 0.10 还是主流，会有很多人重复问的。

**Comment by xuhuan** [comment]
安装了node 的0.11.15 后重新安装再执行就没问题了。
0.11.x还不是稳定版，能否弄个支持0.10的？

**Comment by xuhuan** [comment]
安装了node 的0.11.15 后重新安装再执行就没问题了。
0.11.x还不是稳定版，能否弄个支持0.10的？
