### ISSUE TITLE
less里有ie的hack代码就宕掉

### ISSUE THREAD

**Issue by xuhuan** [spmjs/spm-server#23]
![image](https://cloud.githubusercontent.com/assets/1960194/5896064/7c75d246-a569-11e4-84e5-9f6b9f898747.png)
如题，spm3在编译less的时候有ie的hack代码都可以，为什么这里的却不行？

**Comment by xuhuan** [comment]
难道是因为我本地是多个spm版本的原因？
默认的spm是spm 2。
spm3是spm版本3的命令。

**Comment by sorrycc** [comment]
不知是啥 hack 写法? 试了下简单的没有问题。

```css
h1 {
  _color: @blue;
}
```

**Comment by xuhuan** [comment]
```  
_bottom: auto;
_top: expression(eval(document.documentElement.scrollTop));
```
如上

**Comment by sorrycc** [comment]
改成 

```css
_bottom: auto;
_top: ~"expression(eval(document.documentElement.scrollTop))";
```

https://github.com/less/less.js/issues/293
